### ISSUE TITLE
Increase Code Coverage on `email.js` to 100%

### ISSUE THREAD

**Issue by Furchin** [builtforme/CodeBnb#18]
Right now the [unit test code coverage on email.js](https://codecov.io/gh/builtforme/CodeBnb/src/codecov/email.js) stands at 46%. This issue is to increase that to 100% by proper use of mocks and by adding unit tests.

**Comment by mcclayton** [comment]
I implemented 100% code coverage of email.js here: https://github.com/builtforme/CodeBnb/pull/22
