### ISSUE TITLE
Add Unit Tests and Code Coverage Reports

### ISSUE THREAD

**Issue by Furchin** [builtforme/CodeBnb#6]
Add unit tests and add code coverage reports.

**Comment by lopno** [comment]
I'll do this. I will add the code runner Jest, which also supports code coverage.

**Comment by mcclayton** [comment]
I have a PR open to add Jest and a couple simple tests for email.js here: https://github.com/builtforme/CodeBnb/pull/11

I didn't see your comment when I started working on this @lopno .
If @Furchin like's my PR, it'd be super simple for you to add reporting via istanbul if you want to do that? Otherwise I can handle that as well.

**Comment by lopno** [comment]
@mcclayton No problem. I'll let the author sort it out :)

**Comment by Furchin** [comment]
@lopno and @mcclayton Thanks for _both_ working on this! As I mentioned in #12, #11 came in first and goes further so I've accepted it, but as you both note, coverage could be improved further! Would it be useful if I created another issue tagged hacktoberfest to increase coverage?

**Comment by mcclayton** [comment]
I think that'd be a good idea 👍 You could create a few issues for specific files that could use greater test coverage. That way more people participating in Hacktoberfest can contribute 😄

**Comment by Furchin** [comment]
Alright we should be all set -- I've configured [CircleCI]() as the build system resolving #7 and added reporting of the coverage ya'll added to CodeCov in #17. As mentioned above I've created separate issues -- #18 #19 #20 #21 -- for increasing code coverage on the four js files contained within CodeBnb. I'm going to go ahead and resolve this issue; the four created have been tagged for `hacktoberfest` to assist people with getting their shirts :D
