### ISSUE TITLE
Add CI System

### ISSUE THREAD

**Issue by Furchin** [builtforme/CodeBnb#7]
Likely either CircleCI or TravisCI, we'd like to run the unit tests as part of PR validation, and upon merge to master. The build should fail if:

* Any of the unit tests fail.
* The code coverage drops below what the last merge to master produced

The build should _not_ fail if:
* The code coverage drops below the coverage provided by some other branch which has not yet been merged to master. 

This issue depends on #6 being completed (otherwise it's pointless)!

**Comment by anishkny** [comment]
IIUC, [Coveralls](https://coveralls.io) should be able to cover these requirements, and has good integration with CircleCI/Travis CI. Would that work?

**Comment by Furchin** [comment]
Yup good point although I got Codecov.io working first as #17! Coverage reports should be being published to https://codecov.io/gh/builtforme/CodeBnb now. I added #18 #19 #20 #21 to help bolster the unit tests and the resulting code coverage. Resolving this issue.
