### ISSUE TITLE
AWS Cloud Template

### ISSUE THREAD

**Issue by Furchin** [builtforme/CodeBnb#8]
There's quite a bit of setup involved: an AWS Lambda Function, an IAM role, 2 CloudWatch triggers, and API Gateway with several routes/resources. Rather than setting this all up by hand, it would be nice to have an AWS Cloud template that folks could use to get up and running quickly (along with clear instructions on how to use it).

As a bonus, might be worth investigating if things could be ported to GCE or Azure and provide configuration for those platforms too.

**Comment by apogoryelyi** [comment]
Here is pull request: https://github.com/builtforme/CodeBnb/pull/13 that can address this. @Furchin please take a look.
