### ISSUE TITLE
Add a CONTRIBUTING.md file with contribution guidelines

### ISSUE THREAD

**Issue by Furchin** [builtforme/CodeBnb#9]
Per https://hacktoberfest.digitalocean.com/#resources, we should document some contribution guidelines; there's no reason these couldn't be contributed themselves!

**Comment by hellotunmbi** [comment]
Hi there. Can I work on this?

**Comment by Furchin** [comment]
Absolutely!

**Comment by hellotunmbi** [comment]
thanks for the opportunity. With update you with a pull request

**Comment by felipesousa** [comment]
Hello @Furchin, I made a `pull request` creating a CONTRIBUTING.md file to your project. See here #10 :octocat: 🐙
